### PR TITLE
Modularisation

### LINKED ISSUE #15: Swagger definition
- change from `userID` to `patientID `
- add scopes [example](https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-6-defining-security/)

### LINKED ISSUE #17: Interval field
Add an `interval` input variable to specify time window granularity. If not specified, it should return the smallest time granularity available for the given user.

Suggested values are

- 10 seconds
- 30 seconds
- 1 min
- 10 min
- 1 hour
- 1 day
- 1 week

### LINKED ISSUE #20: How to add new devices
We need to define a mechanism to easily integrate new device.

A solution could be to use a `yml` with the device specification defining on board sensors, mongo db collections and dao interfaces.

### PR DESCRIPTION
**Pull request by fnobilia**
Changed input parameter from `userID` to `patientID` (resolve #15 ).
Sensors end-points support the `Time-Frame` parameter (resolve #17 ).
Define the concept of *Device Catalog* using the configuration file `device-catalog.yml` (resolve #20 ).

### CODE REVIEW

**Comment by blootsvoets** [comment]
Could we use `userId` or `subjectId` instead of `patientId`? Since it is an ID of user in our system, but `patientId` implies that it is a patient, which in many research studies is not the case. In [OpenMHealth header](https://github.com/openmhealth/schemas/blob/master/schema/omh/header-1.1.json), `user_id` is used. `subjectId` would also be fine in the context of a research study, although it would be less appropriate for self-organized data gathering.

**Comment by fnobilia** [comment]
This was discussed during a call with the Front-end meeting a few moths ago. I see your point: `userId` is more general and for this reason it was initially defined as `userId`.
@herkulano asked for this change.

**Comment by herkulano** [comment]
@fnobilia @blootsvoets I agree with `subjectId`. `userId` can easily be mistaken or confused with the user of the applications, either in the dashboard or the questionnaire.

//cc @kerzmaximilian

**Comment by fnobilia** [comment]
Changed here RADAR-CNS/RADAR-RestApi@254acef

**Pull request merged**
